version: 2.1
jobs:
  shrp_compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          name: Prepare building env
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison build-essential curl flex g++-multilib gcc gcc-multilib clang git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev unzip openjdk-8-jdk python ccache libtinfo5 repo libstdc++6 wget libssl-dev rsync
           mkdir -p ~/bin
           curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
           chmod a+x ~/bin/repo
           git config --global user.name "Giovix92"
           git config --global user.email "ggualtierone@gmail.com"
           git config --global color.ui false
      - run:
          name: Clone telegram.sh & repo init
          command: |
           wget https://raw.githubusercontent.com/SHRP-Devices/ci_scripts/master/.circleci/build.sh
           git clone https://github.com/fabianonline/telegram.sh telegram/
           source build.sh
           tgsay "• Giovix92 CI - SHRP •" "Rollin' up!"
           repo init -u git://github.com/SKYHAWK-Recovery-Project/platform_manifest_twrp_omni.git -b 9.0 --depth 1
      - run:
          name: Remove useless files
          command: |
           cd .repo/manifests
           sed -i '/darwin/d' default.xml
           ( find . -type f -name '*.xml' | xargs sed -i '/darwin/d' ) || true
           git commit -a -m "Bump" || true
           cd ../
           sed -i '/darwin/d' manifest.xml
           cd ../
      - run:
          name: Repo sync
          command: |
           repo sync -c -q --force-sync --no-clone-bundle --optimized-fetch --prune --no-tags -j$(nproc --all)
      - run:
          name: Building time!
          command: |
           source build.sh
           tginit
           export ALLOW_MISSING_DEPENDENCIES=true
           export TW_DEFAULT_LANGUAGE="en"
           export LC_ALL="C"
           export TARGET_ARCH="arm64"
           git clone https://github.com/SHRP-Devices/ci_scripts
           mv ci_scripts/*.sh .
           rm -rf ci_scripts/
           if [ "$lastdev" != "" ]; then
             check=1
             tgsay "• Giovix92 CI - SHRP •" "Lastdevice var set: $lastdev"
           fi
           if [ "$DEVICE" == "" ]; then
             for bdevice in $(ls *.sh)
             do
               export pdevice=$(basename $bdevice .sh)
               if [ "$pdevice" = "$lastdev" ] || [ "$check" != "1" ]; then
                 export USE_CCACHE="1"
                 source build.sh
                 echo $pdevice > lastdevice
                 rm -rf device/
                 mkdir device/
                 tgsay "• Giovix92 CI - SHRP •" "Build started on Circle CI, device: $pdevice"
                 bash $bdevice
                 tgsendzip
                 make clean
                 rm -rf out/
                 repo sync -c -q --force-sync --force-remove-dirty --no-clone-bundle --optimized-fetch --prune --no-tags -j$(nproc --all)
               fi
             done
           else
             export pdevice=$DEVICE
             echo $pdevice > lastdevice
             tgsay "• Giovix92 CI - SHRP •" "Build started on Circle CI, device: $pdevice" "Note: that's a single build mode."
             bash $pdevice.sh
             tgsendzip
           fi
      - run:
          name: Fail.
          command: |
           source build.sh
           export last_device=$(cat lastdevice)
           tgsay "• Giovix92 CI - SHRP •" "Build throwing errors! Last device: $last_device"
          when: on_fail
workflows:
  version: 2.1
  cooking:
    jobs:
      - approve_build:
          type: approval
      - shrp_compile:
          requires:
            - approve_build
